title: Your awesome title
email: your-email@example.com
description: >- # this means to ignore newlines until "baseurl:"
  Write an awesome description for your new site here. You can edit this
  line in _config.yml. It will appear in your document head meta (for
  Google search results) and in your feed.xml site description.
url: "styleguide.animikii.com" # the base hostname & protocol for your site, e.g. http://example.com
github_username:  animikii

# Build settings
markdown: kramdown
theme: minima

kramdown:
  input: GFM
  syntax_highlighter_opts:
    default_lang: html
    css_class: 'highlight'
    span:
      line_numbers: false
    block:
      line_numbers: true
      start_line: 1

source: docs

sass:
  style: compressed

nav:
  - path: communication.md
  - path: ruby/index.md
    subnav:
      - path: ruby/rails.md
  - path: git.md
  - path: liquid.md
  - path: react.md
  - path: sass.md
