title: Animikii style guide
email: info@animikii.com
description: >-
  Welcome to the Animikii style guide where we layout our code conventions,
  patterns and solutions to problems we encounter.
baseurl: ""
url: "styleguide.animikii.com"
github_username:  animikii

# Build settings
markdown: kramdown
theme: minima

kramdown:
  input: GFM
  syntax_highlighter_opts:
    default_lang: html
    css_class: 'highlight'
    span:
      line_numbers: false
    block:
      line_numbers: true
      start_line: 1

# source: docs

sass:
  style: compressed

nav:
  - path: communication.md
  - path: ruby/index.md
    subnav:
      - path: ruby/rails.md
  - path: git.md
  - path: liquid.md
  - path: react.md
  - path: sass.md
